### ISSUE TITLE
hydraulic_linear.C missing in source

### ISSUE THREAD

**Issue by uhucrew** [perabrahamsen/daisy-model#10]
The file "hydraulic_linear.C" is missing in repository, if compiling the source, this error occurs:

`make[1]: *** No rule to make target 'hydraulic_linear.C', needed by 'hydraulic_linear.o'.  Stop.
make[1]: Leaving directory '/root/daisy/obj'
Command exited with non-zero status 2
`

Removing 'hydraulic_linear.C' from line 198 in Makefile fixes compile process but maybe there are other issues with the resulting binary because of missing model.

**Comment by perabrahamsen** [comment]
Thanks for the report, I have added it (and a few other files I had forgotten). It is a stand-alone module, so leaving it out should not affect any setup that doesn't explicitly includes it.

Kind regard,

Per A.
