### ISSUE TITLE
Ubuntu installation instructions

### ISSUE THREAD

**Issue by nordfalk** [perabrahamsen/daisy-model#9]
Theres no install or readme or other accesible documentation in the github project, but see here: https://daisy.ku.dk/download/linux/

As there is no other place I'll note down a recipe I'll do it here:

```
sudo apt install libsuitesparse-dev libboost-dev
git clone https://github.com/perabrahamsen/daisy-model
cd daisy-model
```
Switch to release 5.93.
Edit Makefile and set `SRCDIR = $(PWD)`
```
make linux debian-setup TAG=5.93
sudo gdebi debian/daisy_5.93_amd64.deb 
```
This works on Ubuntu 18.

**Comment by perabrahamsen** [comment]
See https://github.com/daisy-model/daisy
